project_id = "searce-playground"
region     = "us-east4"
cluster_name_suffix = ""
network = "vpc-us-east-4-01"
subnetwork = "subnet-us-east-4-01-01"
ip_range_pods = "pods-subnet"
ip_range_services = "svc-subnet"
compute_engine_service_account = ""
